name: Docker Build and Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        id: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.lalithkumar11 }}
          password: ${{ secrets.lalithdocker123 }}

      - name: Save Docker login state
        id: save-login-state
        run: echo "::save-state name=docker-login::${{ steps.login.outputs.login-state }}"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lalithkumar11/getting-started:latest
          file: Dockerfile

      - name: Restore Docker login state
        id: restore-login-state
        run: echo "${{ steps.save-login-state.outputs['docker-login'] }}" >> $GITHUB_ENV
