name: Docker Build and Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create environment file
        run: echo "DOCKER_USERNAME=${{ secrets.lalithgowda }}" >> .env && echo "DOCKER_PASSWORD=${{ secrets.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 }}" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CONFIG: ${{ github.workspace }}
          DOCKER_ENV_FILE: .env

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: lalithkumar11/getting-started:latest
          file: Dockerfile
