version: 2.1
 jobs:
  build:
    docker:
         - image: circleci/php:7.4-cli
    steps:
         - checkout
         - run:
           name: Build and push Docker image
           command: >
                  echo $lalithdocker123 | docker login -u $lalithkumar11
                  --password-stdin
                  docker build -t $lalithkumar11/my-php-app:$CIRCLE_SHA1 .
                  docker push $lalithkumar11/my-php-app:$CIRCLE_SHA1
